### ISSUE TITLE
root not being defined

### ISSUE THREAD

**Issue by Sam-Hoult** [cferdinandi/gumshoe#10]
commit: ff342ce
Changing this back to include window fixed my gumshoe (commonJS), otherwise root is undefined, making the script fail.

**Comment by cferdinandi** [comment]
Failed using what method of implementing. Based on everything I've read, the current setup is the correct syntax.

**Comment by Sam-Hoult** [comment]
var gumshoe = require('gumshoe/dist/js/gumshoe.js');

  // Gumshoe
  gumshoe.init({
    offset:40
  });

then as root isn't defined, everything trying to access root fails so flops straight away over at:
!!root.addEventListener

Runs through gulp, browserify. (On chrome). Is root supposed to be set elsewhere?

**Comment by cferdinandi** [comment]
@Sam-Hoult - Based on the UMD spec, I was under the impression root is based into the script as an argument. I'm using the [amdWebGlobal pattern](https://github.com/umdjs/umd/blob/master/amdWebGlobal.js) as defined in the [UMD repo on GitHub](https://github.com/umdjs/umd). Am I missing something? I don't use Browserify, so it's definitely a possibility that I screwed something up.

**Comment by cferdinandi** [comment]
This has been fixed...
