### ISSUE TITLE
active class not being applied on link – v4

### ISSUE THREAD

**Issue by williharder** [cferdinandi/gumshoe#106]
Hello, 

I tried quite a few things but it doesn't work. It doesn't add the active class at all. So with my reduced test case I actually get some progress. When the site loads, it apparently detects the first content in view and applies the active class to the first menu item.  But after that, when I'm scrolling the page, nothing happens. 

The site is a barba.js combination with a Sage WordPress dev setup, so it wasn't possible to reduce it any way further without loosing the context of my current application. 
Each time a new view is entered, I am initiating a spy instance or destroying it, when I'm leaving the view. 
The code is not minified and I did log the spy instance, which looks so far like it should – it finds all links and it's depending content. You can have a look here http://kristintrueb.willi-harder.de/projects/test-01/

Help would be so much welcomed <3

**Comment by cferdinandi** [comment]
I can't precisely pinpoint what's wrong, but it's related to your CSS. There's a lot of fixed and absolute positioning going on that's likely breaking the way Gumshoe runs its calculations. If you completely disable CSS, it works as expected. I would start by systematically undoing your CSS until it starts working, at which point, you will have indentified the root issue.

**Comment by williharder** [comment]
Thank you very much for the quick reply. I will do like you said. Thanks again!

**Comment by williharder** [comment]
I found out what caused the issue. When having a custom defined scroll area like in my example and hiding the vertical overflow on html or body, gumshoe will not work. Is it possible to let gumshoe makes its calculation based on a custom defined scroll area?

**Comment by cferdinandi** [comment]
Sorry for the delayed response here... no it is not. Gumshoe only works on the `body`.
