### ISSUE TITLE
First element looses 'active' class on overshoot

### ISSUE THREAD

**Issue by grommas** [cferdinandi/gumshoe#107]
Hi Chris! Thanks for your plugin. I want to use it inside a `position: fixed;` container with `overflow-y: scroll;` and `-webkit-overflow-scrolling: touch;` combined with a [body-scroll-lock](https://github.com/willmcpo/body-scroll-lock). I already changed the scroll event listeners in your script to the related container. Everything works as aspected. The only problem: The first list element will loose the active class for a short moment when scrolling upwards on Safari. (Caused by an overshoot / scroll bounce.) It’s a logical behavior from the browser side, but iritating for the user. Do you have a hint how to solve it? [Here is the CodePen.](https://codepen.io/grommas/pen/pXPwZL)

Cheers, Jakob

**Comment by cferdinandi** [comment]
Hi Jakob - I've got no idea, sorry!
