### ISSUE TITLE
bootstrap tabs and gumshoe conflict

### ISSUE THREAD

**Issue by gummarith** [cferdinandi/gumshoe#11]
I noticed a conflict between bootstrap tabs and gumshoe... the first doesn't work at all 'till gumshoe is loaded. Any idea?

**Comment by cferdinandi** [comment]
Bootstrap's scripts may be waiting for all elements on a page to be loaded before running? You could try using [Tabby](https://github.com/cferdinandi/tabby), my lightweight alternative, instead. All of my script were designed to work together.
