### ISSUE TITLE
Support for body overflow hidden and independently scrolling grid columns?

### ISSUE THREAD

**Issue by agibsen** [cferdinandi/gumshoe#114]
I'm not sure if this case is supported out-of-the-box, if not, it's a feature request:

Suppose I have `overflow: hidden` on `<body>`. Then, inside I have a CSS native grid with a height of `100vh` and two grid columns, one for the navigation and another for the content. Each column has `overflow-y: auto`, thus scrolls independently. GumShoe apparently doesn't work in this case?
Is there currently a setting in GumShoe which could enable this scenario, or would it be a new feature?

**Comment by cferdinandi** [comment]
out of scope for this project, sorry! :)

If you wanted to submit a PR for it, I'd be happy to entertain it, but I can't commit any time to figuring this one out.
