### ISSUE TITLE
Add support for Typescript

### ISSUE THREAD

**Issue by marco910** [cferdinandi/gumshoe#141]
Hi there,

This is a really awesome and easy to use dependency. But unfortunately, the Typescript declarations are missing.
Any ideas how to fix this or can you add this, please?

Thanks!

**Comment by cferdinandi** [comment]
> the Typescript declarations are missing

This kind of implies that they're a required part of a JavaScript project or something needed to run the code.

I don't use TypeScript, so won't be adding support for it. It's just another thing to maintain. Sorry!
