### ISSUE TITLE
Offset not taken in consideration

### ISSUE THREAD

**Issue by christophemarois** [cferdinandi/gumshoe#21]
In version 2.0.0, in `src/js/gumshoe.js` at line `238`

```javascript
// Get current position from top of the document
var position = root.pageYOffset;
```

should be

```javascript
// Get current position from top of the document
var position = root.pageYOffset + config.offset;
```

in order to work with the `offset` param. I suspect this is only a mistake, because `config.offset` isn't used anywhere in version 2.0.0

**Comment by digHBS** [comment]
Doh, good catch. I'll get this fixed this week. Thanks!

**Comment by cferdinandi** [comment]
Doh, good catch! I'll get this fixed this week.

**Comment by cferdinandi** [comment]
Fixed. https://github.com/cferdinandi/gumshoe/pull/22

**Comment by christophemarois** [comment]
My pleasure! Keep up the good work.
