### ISSUE TITLE
Main script reference in package.json

### ISSUE THREAD

**Issue by asalisbury** [cferdinandi/gumshoe#24]
The "main" property in `package.json` is set to the `dist/` directory rather than the main script within that directory. I created an issue here only because in Webpack and similar tools, the script has to be explicitly defined, or else it has to be manually changed. (I also noticed in your smooth-scroll that you reference the full path to the file.) Thanks!

**Comment by cferdinandi** [comment]
Thanks, didn't know that! I'll make the update when I have a spare moment.

**Comment by cferdinandi** [comment]
@asalisbury I obviously haven't tackled this yet, but how does this work for a plugin that has both JS and CSS components? I'm assuming you point to the JS file only, and that Webpack does not load CSS?

**Comment by cferdinandi** [comment]
Fixed with https://github.com/cferdinandi/gumshoe/pull/27. Sorry for the delay.
