### ISSUE TITLE
Used on Swift.org

### ISSUE THREAD

**Issue by paulyoung** [cferdinandi/gumshoe#25]
Thought you might like to know that, and maybe put it in the README.

**Comment by cferdinandi** [comment]
Whhhaatttt? Wow, thanks for the heads up. Thanks INCREDIBLE.

**Comment by paulyoung** [comment]
For what it's worth:

![screen shot 2015-12-04 at 8 57 04 pm](https://cloud.githubusercontent.com/assets/84700/11601237/9e55325c-9ac9-11e5-87c2-7e508c0e9c86.png)

**Comment by cferdinandi** [comment]
I saw! Headed right over there to view source. Tickled pink!

**Comment by paulyoung** [comment]
Congrats.

**Comment by cferdinandi** [comment]
Added to readme. Cheers again for the heads up!
