### ISSUE TITLE
Unit without reference to the menu

### ISSUE THREAD

**Issue by senja006** [cferdinandi/gumshoe#28]
In the current project, I get the following situation. Any block for which no references in the menu. And it turns out that when you scroll to this block incorrect items are marked on the menu. I would like to at this point, no item was not marked active.

**Comment by cferdinandi** [comment]
Demo link please.

**Comment by senja006** [comment]
http://armature.yarkevich.ru/. For the first block of content is not a menu item. The project is under development. Please only look with chrome

**Comment by cferdinandi** [comment]
So if I'm understanding you correctly:

1. There are blocks of content on your page.
2. One or more of those blocks is an independent section not linked to in the header navigation.
3. When someone scrolls into that block, you want no navigation element to active.

Is that correct? If so, Gumshoe does not support this. It is intended to hold the currently active navigation as active until another content section replaces it.

**Comment by veganista** [comment]
The work around for this is to put a hidden element in your navigation list that links to your first section

**Comment by senja006** [comment]
Now I did. But I do not like this method. It would be better if just cleaned activity class

**Comment by cferdinandi** [comment]
I agree - that would be better. A hidden nav element is also potentially bad for accessibility. But stripping the active class if no content block is active adds quite a bit more complexity to an already complex script. Marking this won't fix. Sorry!

**Comment by veganista** [comment]
I initially thought that it would be bad for accessibility, but i simply have a link for "Home" which i hide with CSS, if screen readers hit it its still a working a link with the correct labels.

Similar to having a "Skip to content" link that only screen readers see, plus you could always add aria-hidden to it.
