### ISSUE TITLE
Doesn't adapt to position: fixed headers

### ISSUE THREAD

**Issue by colbin8r** [cferdinandi/gumshoe#29]
Chris, I really love the simplicity of this library. Thanks for making it open source for us all to enjoy! :smile:

Just thought that I would point out, as I found out in one of my projections, the `getOffsetTop` won't work for sticky headers that are fixed with `position: fixed` because the `offsetTop` property of the element itself is never taken into consideration. Consider adding an `else` statement to the conditional that accounts for it. For example:

```javascript
var getOffsetTop = function ( elem ) {
	var location = 0;
	if (elem.offsetParent) {
		do {
			location += elem.offsetTop;
			elem = elem.offsetParent;
		} while (elem);
	} else {
		location = elem.offsetTop;
	}
	location = location - headerHeight - settings.offset;
	return location >= 0 ? location : 0;
};
```

The original function won't work with fixed headers because, [in Webkit, elements that are `position: fixed` have no `offsetParent`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent); therefore, the `location` never has the element's `offsetTop` property included. With a fixed position header, the `offsetTop` property is all `location` needs to be set to before accounting for the `headerHeight` and `settings.offset`.

**Comment by cferdinandi** [comment]
Wow, such a small thing I never would have caught since I generally don't use sticky headers. I noticed you issued a PR for this, too. Thanks!

**Comment by cferdinandi** [comment]
Fixed with https://github.com/cferdinandi/gumshoe/pull/32
