### ISSUE TITLE
Script doesn't work with RequireJS

### ISSUE THREAD

**Issue by hiulit** [cferdinandi/gumshoe#3]
Hi there,

I've been trying to add the script using
```
require(['libs/gumshoe/dist/js/gumshoe'], function(gumshoe) {
	gumshoe.init();
});
```

and I kept getting an `undefined` so I tried and modified the script, like this:

```
 (function (root, factory) {
	 'use strict';
	 if (typeof define === 'function' && define.amd) {
		 define([], factory(root));
	 } else if (typeof exports === 'object') {
		 module.exports = factory(root);
	 } else {
		 root.gumshoe = factory(root);
	 }
 }(window || this, function (root) {

    // The whole script goes here

}));
```

and now it maggically works! :smile: At least for me...

Is that a thing?

I took the code from another script I was using in my project and as I said, it's working for me, I don't know, hehe!

**Comment by cferdinandi** [comment]
Wow, really good catch. I had made that update in a few other scripts, but must have used an old template when starting this one up. I'll make the change and push.

Thanks @hiulit!

**Comment by hiulit** [comment]
You're welcome @cferdinandi ;)

**Comment by jonathanwkelly** [comment]
Thanks @cferdinandi , @hiulit

**Comment by cferdinandi** [comment]
Fixed
