### ISSUE TITLE
Is there a way to establish a navigation including a sub-nav?

### ISSUE THREAD

**Issue by julkuh** [cferdinandi/gumshoe#33]
To see what I mean check [this pen](http://codepen.io/makotot/pen/YyRXOQ) or the [Bootstrap](http://getbootstrap.com/css/) Documentation. Would be awesome!

**Comment by cferdinandi** [comment]
Hi there - so I took a look into this, and it looks like Gumshoe is 90% there in support of this.

Currently, you can actually use subnavigation and the script detects it and adds the active class. BUT, unlike your demo (and Bootstrap), it doesn't also add a class to the parent element.

This should be relatively easy to add, and I'm happy to do so, but... in the interest of setting expectations, this script is low-priority for me at the moment as I work on a few other projects more relevant to my core business. 

I will address this, but it might be a little while.

**Comment by amdad** [comment]
That would be nice.

**Comment by SimonFricker** [comment]
+1

**Comment by cferdinandi** [comment]
Three years later, I finally added support for this with v4.x. Sorry for the (crazy long) delay!

https://github.com/cferdinandi/gumshoe/releases/tag/v4.0.0

**Comment by cferdinandi** [comment]
Oh, here are the docs on nested navs: https://github.com/cferdinandi/gumshoe#nested-navigation

**Comment by amdad** [comment]
Thank you very much man!

**Comment by amdad** [comment]
Thank you very much man! 

But for example when you click on Doc,  Dickory is active instead of Doc itself. 
On old default demo, the same issue was visible with Miney, Mo.  How you make it 95vh so problem are not visible there anymore. Seems like it miscalculate something on short distances.

**Comment by cferdinandi** [comment]
I'm not seeing that on either Chrome or Firefox. It's possible the CDN is serving you v4.0.0. I pushed a quick update to calculations in v4.0.1 that fix them. Can you double check and let me know by visiting this link and telling me what version is in the header?

https://cdn.jsdelivr.net/gh/cferdinandi/gumshoe@4/dist/gumshoe.polyfills.min.js

**Comment by amdad** [comment]
gumshoe v4.0.0  it says

**Comment by amdad** [comment]
Thank you, v4.0.1 works flawless.

**Comment by cferdinandi** [comment]
Ah sorry about that. JSDelivr is an awesome service, but sometimes it caches older versions for a bit longer than I'd like. Glad v4.0.1 is working as expected!

**Comment by amdad** [comment]
I use https://unpkg.com/ after [desandro](https://github.com/desandro) moved to it. It takes packs from NPM, so can you add new version there too, please?  https://www.npmjs.com/package/gumshoejs Or it should show up auto somehow?
