### ISSUE TITLE
offset required

### ISSUE THREAD

**Issue by altano** [cferdinandi/gumshoe#35]
Hey there,

I'm testing in Chrome and I find myself having to use {offset: 2} because:

1. I have `<h1 id="someHeader">...</h1>`.  When I go to #someHeader:
    1. pageYOffset = 8151
    1. nav.distance = 8152
    1. document.getElementById("Testing").getBoundingClientRect().top = 0.859375
I didn't have time to dig in but I think there is some sub-pixel issue here causing it to round up to 8152.
1. The code: `if ( nav.distance < position ) {`  Shouldn't this be `<=` not `<`?

With an offset of 2, 8152 becomes 8150 and can pass the `nav.distance < position` check which makes it so that navigating to #someHeader actually highlights the right nav element.

**Comment by cferdinandi** [comment]
You're absolutely right. Thanks for this! Will get this knocked out.

**Comment by cferdinandi** [comment]
Will be addressed in https://github.com/cferdinandi/gumshoe/pull/41
