### ISSUE TITLE
media queries

### ISSUE THREAD

**Issue by altano** [cferdinandi/gumshoe#36]
Hey There,

This isn't really so much a bug as it is a heads-up.  I was having trouble with your code which I tracked down to the gumshoe.init() method executing before my media query was kicking in and moving the nav to be fixed position, so all the distances were off.

I was able to fix this with the tiny snippet of code at https://github.com/tylergaw/media-query-events/blob/master/js/mq-events.js

Using that snippet, I added this single line to gumshoe.js:

	// Listen for events
	root.addEventListener('resize', eventThrottler, false);
	root.addEventListener('scroll', eventThrottler, false);

	// Listen for media query changes and pretend they're a resize
	root.mqEvents(eventThrottler.bind(null, {type: 'resize'}));   // <=============

You might either want to integrate this code into gumshoe OR at least mention that gumshoe doesn't listen for media query events, only window resize, so consumer code would have to implement the same thing I did if they're using media queries.

**Comment by cferdinandi** [comment]
The only reason this should be happening is if you're initing the script before your stylesheet has loaded, right? Or am I missing something?

**Comment by altano** [comment]
My stylesheet is in <head> and I'm initializing gumshoe at the bottom of my DOM.  I can't find any documentation about when media queries should kick in and how to wait for that event, which is why I took the approach mentioned above.

**Comment by cferdinandi** [comment]
Can you provide a reduced test case I can look at?

**Comment by cferdinandi** [comment]
@altano Can you provide me with a reduced test case so I can take a look and see if this is the right solution or if something else is happening?

**Comment by altano** [comment]
I had trouble reproducing on JSFiddle but that's because you can't configure how CSS gets dropped onto the page. I'll work on reproducing it again I a custom environment tonight.

On Apr 12, 2016, at 2:03 PM, Chris Ferdinandi <notifications@github.com<mailto:notifications@github.com>> wrote:


@altano<https://github.com/altano> Can you provide me with a reduced test case so I can take a look and see if this is the right solution or if something else is happening?

-

**Comment by altano** [comment]
I figured it out, finally!  Apparently this is a conflict with [mqGenie](https://github.com/stowball/mqGenie).  mqGenie is asynchronously doing its work on DOMContentLoaded(), which results in the media queries being modified *after* gumshoe was initialized.  I fixed the problem by moving gumshoe.init() into a DOMContentLoaded event listener.

BUT, interestingly, the gumshoe positions of the headers were still wrong, by ~110px.  I couldn't figure out why, I even checked the images that appeared above the headers and that wasn't the problem.

I ultimately fixed it by moving gumshoe.init() into a window.load event listener.  That means the nav won't have scroll-spy support until all the images on the page are done loading, which is sub-ideal, but I couldn't find the source of this 110px discrepancy.

**Comment by altano** [comment]
^^ Just to be clear, when I say the gumshoe positions of the headers were wrong by 110px, I don't mean gumshoe incorrectly calculated them.  I mean that the headers were being pushed down AFTER gumshoe.init() executed by ~110px and I don't know why.

**Comment by cferdinandi** [comment]
@altano Since gumshoe is just adding styles (namely, the `.active` class), you might start by looking at your stylesheet to see if there were maybe some style conflicts or something.
