### ISSUE TITLE
Uncaught ReferenceError: eventHandler is not defined

### ISSUE THREAD

**Issue by hiulit** [cferdinandi/gumshoe#4]
I had to comment/remove this piece of code:

```
// Remove event listeners
    document.removeEventListener('resize', eventHandler, false);
    document.removeEventListener('scroll', eventHandler, false);
```
because `eventHandler` doesn't exist anywhere.

Did you maybe mean `eventThrottler`?

Or maybe forgot to create `eventHandler`? Because I've seen it in your other project `smoothScroll` that you have them there...

**Comment by cferdinandi** [comment]
Bah, I must have been a bit too hasty in pushing this script out. Thanks @hiulit. Will update asap.

**Comment by cferdinandi** [comment]
Sorry for the delay on this. Fixed via https://github.com/cferdinandi/gumshoe/pull/9.
