### ISSUE TITLE
Incorrect header considered "active" on page reload

### ISSUE THREAD

**Issue by ezzatron** [cferdinandi/gumshoe#42]
Please see http://eloquent-software.com/phony/latest/#mock-handle-substitution for an example of this issue.

When you first load up the page, you'll see that the correct heading (Mock handle substitution) is highlighted. But if you reload the page, the active header will switch to the previous heading (Verification handles).

Any ideas what could be causing this?

**Comment by cferdinandi** [comment]
I'm actually not seeing this behavior... or, well, I am, but with a catch.

When I click reload, the page is highlighting the previous heading for a very brief moment, and then switching the one below it. I've noticed that there's some content being generated by JavaScript that causes the page to shift a bit after it loads. 

I suspect this may be the cause. The previous heading/content really is the primary one on initial load, but as soon as JS injects more content, the right heading slides into place and the highlighting updates.

**Comment by ezzatron** [comment]
Weird. I tried this in multiple browsers, and it only seems to happen in Chrome. Under Safari I get the same behaviour as you describe. Firefox doesn't seem to have any issue.

There's definitely dynamic content changes done by JavaScript, but I thought I'd been pretty careful to call `gumshoe.setDistances()` whenever this occurs.

Does it happen for you under Chrome?

**Comment by cferdinandi** [comment]
Chrome is actually the browser I tested in. Could you grab a screen capture for me of what's happening? That might help me debug?

**Comment by ezzatron** [comment]
Okay, here we go: https://gfycat.com/SourFearlessAmericanwarmblood

**Comment by ezzatron** [comment]
Okay, I *think* I've got it figured. Not sure the exact cause, but I was calling `gumshoe.setDistances()` before `gumshoe.init()` in one instance. Ensuring that those are called in the correct order makes it behave (for now).

I'm just pushing the change out, then I'll double check, and close if all is well.

**Comment by cferdinandi** [comment]
Phew, glad you (hopefully) got this figured out, and sorry I wasn't able to be of more help here. I probably should have looked at what methods you were calling as part of the debug.

**Comment by ezzatron** [comment]
No worries, thanks for the help. Seems fine now.

**Comment by cferdinandi** [comment]
Awesome! Thanks for updating the issue. Cheers!
