### ISSUE TITLE
Fixed header on scroll

### ISSUE THREAD

**Issue by jasonbradberry** [cferdinandi/gumshoe#46]
Hi Chris.

I'm running into some issues with a fixed header for a nav for which becomes fixed when it scrolls past the top of the viewport. It seems to cause the calculations to fail, as they don't seem to include the fixed header height because it's not fixed on page load.

Would the script be easy to modify to support this?

Thanks

Jason

**Comment by cferdinandi** [comment]
Hi Jason - When the header scrolls into/out-of view, you could reinit gumshoe to redo the calculations. Alternatively, you could manually pass in an offset equal to the height of the eventual fixed header.

There's a huge performance hit on calculating heights and distances, especially while scrolling, so I deliberately avoid calculating the fixed header height through the scroll process.
