### ISSUE TITLE
Do I need both Gumshoe and Smoothscroll

### ISSUE THREAD

**Issue by shofer4eto** [cferdinandi/gumshoe#51]
Do I need both Gumshoe and Smoothscroll libraries in order to use both the Gumshoe navigation and the custom scrolling events of Smoothscroll? They both seem to use  common functionalities for the actual animated scrolling don't they? Thanks!

**Comment by cferdinandi** [comment]
Yea, you need both. They work quite well together, but they're designed as standalone scripts that can be used independently of each other in conjunction with our scripts.
