### ISSUE TITLE
Assigning the "activeClass" to more than one selector

### ISSUE THREAD

**Issue by shofer4eto** [cferdinandi/gumshoe#52]
Hi there,

Looking to apply the gumshoe both to a top navigation header and a Dotted Side Navigation.
Either one works fine but when I target both items with the selector param (either unifying them or adding separating by comma) only the second one works. I assume this has to do with removing the active class from all other elements but the current one. 
How could I achieve assigning the class to 2 different elements in 2 different navs?
Thanks! :)

**Comment by cferdinandi** [comment]
At present you actually can't. The way the script is written, calling `init` cancels out any previously existing one.

There are different ways to structure the plugin to avoid this, but it would require me to rewrite some stuff, and I don't have time to commit to that at the moment.

Sorry about that!

**Comment by shofer4eto** [comment]
I understand you are busy, still - thanks for the great plugin! :)
I could try to do it myself ... From what I understand I could mod the "deactivateCurrentNav" method to possibly walk only items in the current menu tree? Would that do the trick?

Quick question - is the Minified version of the script in the DIST folder somehow different than the regular one? Couldn't seem to find the "deactivateCurrentNav" method in there?

Thanks again for your work and time spent, it's well appreciated! :)

**Comment by cferdinandi** [comment]
The script will destroy any current implementation if you try to reinit it with a different selector. You might be able to most easily hack this by just removing the `destroy` method. I think that alone would get you what you're looking to do.

If you decide not to do that or it doesn't work, on `init`, the script grabs all of the nav items and catalogs and crawls them as you scroll. Then it activates just the first one that matches. You'd need to make it not bail once it finds a match, and probably modify `deactivateCurrentNav` as well.

The minifier I use is very aggressive, so it changes all of the non-public function names. Anything that can be called with `gumshoe` retains its name (`gumshoe.init()`, `gumshoe.destroy()`, etc.), while anything that's just set as a `var` gets it's name changed to a single character to reduce filesize.

So `deactivateCurrentNav` might get renamed `g`, for example. As such, you definitely want to work with the `src` version of the file, or at least the unminified `dist`.
