### ISSUE TITLE
link with class active is skipped when section heights in vh

### ISSUE THREAD

**Issue by chromosapiens** [cferdinandi/gumshoe#53]
Hi!

I appreciate much your work. Smooth scrolling works great and gumshoe is the perfect complement. However, I am having the issue that one link is skipped (the problem seems to be similar to #37).

The script does work as intended when I use absolute heights for the sections (which is not an option). But with `height: 100vh` it skips the second link. Is there a solution for that?

I set up something so you can see yourself [servertest.at/senoner](servertest.at/senoner).
username: external
pw: ext1

I hope you have an idea.
Thanks in advance!
CS

**Comment by cferdinandi** [comment]
1. That is bizarre! Never seen that before.
2. THANK YOU for providing a working demo link.
3. I'll take a look at this this week. Sorry it's taken me a little while to get back to you.
4. I love your username!

**Comment by cferdinandi** [comment]
v4.x was just released, and uses an entirely different approach that should fix this issue for you: https://github.com/cferdinandi/gumshoe/releases/tag/v4.0.0
