### ISSUE TITLE
Script doesn't work in generator-webapp.

### ISSUE THREAD

**Issue by sincu** [cferdinandi/gumshoe#54]
Hello. When I'm trying to use gumshoe in scaffold generator-webapp it doesn't work.

`Uncaught TypeError: Cannot read property 'window' of undefined`
`Uncaught ReferenceError: gumshoe is not defined`

When I load script from CDN everything works fine. And everything works when I doesn't use generator-webapp, just static files.

What can cause that error?
I tried to place <script> in head, in beginning of the body and at the end. Doesn't work in that scaffold. I'm confused, plz help!

**Comment by cferdinandi** [comment]
That's me being an idiot. In several cases I reference `window`, but with the UMD wrapper (which allows the script to work in things like Webpack), it should be `root`. I'll push a fix later today. Sorry about that!

**Comment by sincu** [comment]
No, man, the idiot it's ME!!!

I must use BOWER, and vendor.js in that scaffold!

Now everything works fine.

**Comment by cferdinandi** [comment]
Oh all good. You helped me find a bug I didn't know existed. Thanks!

https://github.com/cferdinandi/gumshoe/pull/55
