### ISSUE TITLE
Last item always active when scrolled fully at bottom

### ISSUE THREAD

**Issue by lmgonzalves** [cferdinandi/gumshoe#56]
Hey, first I want to thank you for this awesome library!
An image is better than words. Here I've removed the `br` tags below "Moe" to point out the issue.
Thanks in advance!

![issue](https://cloud.githubusercontent.com/assets/12473993/22006690/341eccae-dc3b-11e6-8405-901debded9db.gif)

**Comment by cferdinandi** [comment]
That is the expected/intended behavior. Otherwise, that item would never be active.
