### ISSUE TITLE
Allow for throttle/delay in setting active nav item

### ISSUE THREAD

**Issue by matthewmcvickar** [cferdinandi/gumshoe#57]
I am using your Smooth Scroll script alongside Gumshoe. I have a long document with a sidebar containing the table of contents, and when I click on a link in the sidebar, all of the links between the active item and the newly-clicked item get highlighted for a fraction of a second as they are marked as active. It's distracting and I want to avoid it. Is there a way to make it so the active nav item is only updated every `x` seconds so that scrolling doesn't activate a series of items until it's slowed down?

**Comment by cferdinandi** [comment]
There's actually a delay on scroll events already, but it's only 66ms to provide smooth 24fps animation.

https://github.com/cferdinandi/gumshoe/blob/master/dist/js/gumshoe.js#L338-L363

This is an interesting potential setting for the script, but candidly I don't have the time right now to do anything beyond bug fixes.

You may want to fork the script and change the event throttler to better suits your needs. Would that work?

**Comment by cferdinandi** [comment]
@matthewmcvickar Any thoughts on above? I ended up putting together a simple little helper method that detects when scrolling stops and only then runs a function: https://github.com/cferdinandi/scrollStop

In this way, we could wait until after the scroll to highlight the nav (as an optional setting).

**Comment by matthewmcvickar** [comment]
@cferdinandi This sounds perfect! I'm sorry I haven't gotten back to you—been caught up in work. **scrollStop** looks perfect. Do you want me to try to work this into the pull request, or would you prefer to do the integration yourself?

**Comment by cferdinandi** [comment]
@matthewmcvickar No worries! I'm having one of those weeks, too...

If it's all the same to you, I think I'll fork the changes you made and modify them with the above update. I have a specific approach in mind that will save a byte or two in file size.

**Comment by matthewmcvickar** [comment]
@cferdinandi Sounds good to me. I'll review at what you do as an educational endeavor.

**Comment by cferdinandi** [comment]
Merging https://github.com/cferdinandi/gumshoe/pull/59 as soon as all tests pass

**Comment by cferdinandi** [comment]
If you're curious how I set this all up:

1. Updated the variable name to `scrollDelay` and made it a boolean.
2. Added a simple `if` statement in the `init` function to check if `scrollDelay` is `true` or `false`.
3. If `false` (the default) proceed as normal.
4. If `true` hook into a new `scrollStop()` function (a simplified version of that helper function I shared) that runs our methods *after* scrolling has ended.

I chose to not use that helper function with a callback to save 3 or 4 lines of code. It makes an unimportant difference in total file size, but... I couldn't help myself.

**Comment by cferdinandi** [comment]
Oh... and I chose to do the `if`/`else` check in `init()` instead of `eventThrottler()` for performance reasons. This way we check our settings once instead of continuously throughout the scroll event.

**Comment by matthewmcvickar** [comment]
This is great; thank you so much for putting this together. It’s been a pleasure working with you.

**Comment by cferdinandi** [comment]
Likewise! This is a great new feature, and I learned how to do something new. Cheers!
