### ISSUE TITLE
A script lib I made to compliment gumshoe

### ISSUE THREAD

**Issue by danielhaim1** [cferdinandi/gumshoe#70]
I'm in the process of creating a client dashboard that automatically appends links to header and assigns unqiue ids to the parent sections and wanted to share it, incase anybody wants to create something similar or finds use in it it's available here: https://codepen.io/danielhaim1/pen/pwXJLp

**Comment by cferdinandi** [comment]
Cool! Given that my focus is on framework and library-free tools, and this uses jQuery, I probably won't link to it in the README. But thanks for sharing.
