### ISSUE TITLE
NPM Versioning displays Github-Link

### ISSUE THREAD

**Issue by acac01** [cferdinandi/gumshoe#75]
Hello 
I've noticed that the version number in the package.json is not displayed correctly, instead a github link shows up:
![image](https://user-images.githubusercontent.com/38219548/38505243-0222f44a-3c17-11e8-9fbd-7b7e905ef873.png)

"npm outdated" reports that it is at version 3.5.0, while hovering in Visual Studio Code reports "0.2.1".
The newest version (according to "npm outdated") is just "git".

There seems to be something majorly off with the versioning here, could you please look into that?

**Comment by cferdinandi** [comment]
This project is not hosted on NPM, and `gumshoe` on NPM is not this project. You can use NPM to install packages from GitHub, and even get specific versions using version tags (which I've been sure to include).
