### ISSUE TITLE
Completely wrong calculations

### ISSUE THREAD

**Issue by strarsis** [cferdinandi/gumshoe#77]
On a onepager site gumshoe detects sections much later (with much 
more vertical offset) than they are actually positioned on the page.

**Comment by cferdinandi** [comment]
Reduced test case please https://css-tricks.com/reduced-test-cases/

**Comment by cferdinandi** [comment]
Closed due to inactivity.

**Comment by strarsis** [comment]
@cferdinandi: This is hard to reproduce in a reduced test case.
I will post a sample when I manage to reproduce the issue in it.
