### ISSUE TITLE
Fails on server side

### ISSUE THREAD

**Issue by lkostrowski** [cferdinandi/gumshoe#78]
Hi

I tried to use gumshoe on my nextjs app. Unfortunately sole import of gumshoe end with `document is not defined` error, since it's running on the server. I believe code shouldn't run anything until `init()` get's triggered

**Comment by cferdinandi** [comment]
Good catch. This PR should fix it: https://github.com/cferdinandi/gumshoe/pull/79

v3.5.1 now released.

**Comment by lkostrowski** [comment]
Looks good, thanks mate ;)
