### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by leonardofaria** [cferdinandi/gumshoe#80]
Hi

First of all, good job!

I noticed someone already asked this (https://github.com/cferdinandi/gumshoe/issues/72) but do you mind publishing this in NPM as gumshoejs (or another name since gumshoe is a package already)?

NPM has a few problems in installing packages from git (https://github.com/npm/npm/issues/17379) so it would be great if your package was living there. My colleagues thought in forking it and publishing it but it would be better you do it.

Thanks in advance.

**Comment by cferdinandi** [comment]
Not advertised anywhere, but it's already there under `gumshoejs`: https://www.npmjs.com/package/gumshoejs

That said... I won't be maintaining that going forward. So it won't get any future updates.

**Comment by DanielRuf** [comment]
3.5.1 is not yet there. Can you publish it on npmjs?

**Comment by DanielRuf** [comment]
3.5.1 is not there. Can you publish it on npmjs?

**Comment by cferdinandi** [comment]
See above

**Comment by cferdinandi** [comment]
I maintain several dozen OSS projects. What's *just* one extra CLI command to you is a maintenance nightmare for me.

**Comment by DanielRuf** [comment]
Sorry, I was not aware of this. Could you need additional maintainers, should we install cferdinandi/gumshoe instead of using the package name or create a fork?

Please let me know what we can do here.

**Comment by cferdinandi** [comment]
Honestly, this is just not a thing I'm interested in supporting.

Additional install options include using NPM to pull directly from GitHub (supports versions using GitHub tags) or via CDN from JSDelivr: https://www.jsdelivr.com/package/gh/cferdinandi/gumshoe
