### ISSUE TITLE
Race condition when gumshoe is destroyed

### ISSUE THREAD

**Issue by Joebourne** [cferdinandi/gumshoe#83]
It is possible for `gumshoe` to be destroyed while the timeout of `scrollStop` is still in progress. 

```js
eventTimeout = setTimeout(function() {
    gumshoe.setDistances();
    gumshoe.getCurrentNav();
}, 66);
```

As a result, there is a race condition and an error is thrown as `gumshoe` is undefined.

This happens in React when the component using `gumshoe` unmounts (and destroys `gumshoe`), but this may well happen in other environments too.

**Comment by cferdinandi** [comment]
[I just released version 4.x](https://github.com/cferdinandi/gumshoe/releases/tag/v4.0.0), which should hopefully fix this issue.

If not, let me know and I'll reopen the ticket though.
