### ISSUE TITLE
Dynamically added anchor links

### ISSUE THREAD

**Issue by davshoward** [cferdinandi/gumshoe#87]
Is it possible to get gumshoe to work with links added dynamically?

**Comment by cferdinandi** [comment]
With a refactor I have planned it should. 

Today, you can get kind of there by destroying the current initialization and reinitializing after the element is added.

```js
// Destroy
gumshoe.destroy();

// Add your elements...

// Reinit
gumshoe.init();
```

**Comment by cferdinandi** [comment]
Hi @davshoward  - I just released v4.x, which now has a new public API method to make this easier.

After adding your dynamic content, [run the `setup()` method](https://github.com/cferdinandi/gumshoe#setup) to tell Gumshoe to recognize the new elements.

```js
var spy = new Gumshoe('.your-selector a');

// After adding dynamic content
spy.setup();
```

No need to `destroy()`/`init()`—the script will figure it out and keep going.
