### ISSUE TITLE
Apply multiple classes

### ISSUE THREAD

**Issue by guifelix** [cferdinandi/gumshoe#88]
It would be great if it was possible to add multiple active classes to the desired element.

My personal site is built with [tailwind](https://tailwindcss.com) and since tailwind is about putting classes and not writing CSS, I had to put multiple classes on my element to style it. But in order to get the desired hover effect, I must apply multiple classes on it.

**Comment by cferdinandi** [comment]
I get it. I LOVE utility classes, too, and it's how I build most of my sites as well.

But for maximum efficiency and ease of code base, Gumshoe will likely continue to support just one class per element for the time being. Implementing multiple classes adds a bit more complexity to the code for what feels like an edge case.

**That said...** [Gumshoe now emits custom events](https://github.com/cferdinandi/gumshoe#custom-events) that you could hook into to add/remove additional classes if desired.

```js
// Add classes to active link
document.addEventListener('gumshoeActivate', function (event) {
	event.target.classList.add('another-class');
	event.target.classList.add('and-another-one');
}, false);

// Remove classes from deactived link
document.addEventListener('gumshoeActivate', function (event) {
	event.target.classList.remove('another-class');
	event.target.classList.remove('and-another-one');
}, false);
```
