### ISSUE TITLE
webpack cannot find gumshoe dependency (v4.0.1)

### ISSUE THREAD

**Issue by strarsis** [cferdinandi/gumshoe#94]
After installing gumshoe v4.0.1 from Github repository 
(as that release hadn't been published to npm),
webpack fails to find it:
```json
    "gumshoe": "https://github.com/cferdinandi/gumshoe.git#v4.0.1",
````
```js
import Gumshoe from 'gumshoe';
````
````
This dependency was not found:
* gumshoe in ./resources/assets/scripts/routes/common.js
To install it, you can run: npm install --save gumshoe
````
In `node_modules` there is a `gumshoe` directory for the `gumshoe` v4.0.1 module.

**Comment by cferdinandi** [comment]
Gumshoe uses UMD, but doesn't export anything, so I'm not entirely sure this will actually work.

I'm not a webpack user, so... I'm not really sure how to advise here.

**Comment by strarsis** [comment]
```js
import 'gumshoe/src/js/gumshoe/_closest.polyfill';
import 'gumshoe/src/js/gumshoe/_customEvent.polyfill';
import Gumshoe from 'gumshoe/src/js/gumshoe/gumshoe';
````

**Comment by cferdinandi** [comment]
I'm confused. Those should be baked into the compiled `dist`. Where you attempting to load from the `src` directory?

**Comment by strarsis** [comment]
@cferdinandi: This may be an explanation. 
In [`package.json`](https://github.com/cferdinandi/gumshoe/blob/master/package.json#L5) the path in `main` is wrong: `"main": "./dist/js/gumshoe.min.js",`
But the the main distribution file is in `./dist/gumshoe.min.js` instead, hence webpack can't find it.
Though for webpack I would prefer the unminified source files anyway as I can then use the full source code for debugging and webpack can tree-shake/minify the source with its own methods/options.

**Comment by cferdinandi** [comment]
Ah, that's a bug I can fix. Thanks!

**Comment by cferdinandi** [comment]
I fixed the build path while making some documentation updates and just noticed your PR. Sorry about that!
