### ISSUE TITLE
Headers instead of section divs

### ISSUE THREAD

**Issue by edemaine** [cferdinandi/gumshoe#97]
Have you considered supporting the use-case of headers (like `<h1>`, `<h2>`, etc.) implicitly defining sections (the interval between one header inclusive and the next header exclusive), instead of explicit section `<div>`s?  This seems like a common use-case, e.g., the output of various Markdown translators, and is presumably addable via an option.  If there's interest, I may be able to contribute a PR.

**Comment by cferdinandi** [comment]
This would fundamentally change the way the script works today. 

The last version had a set up kind of like this,  and it was fraught with an accuracy. 

 I can see the appeal, but I’m worried about implementation

**Comment by cferdinandi** [comment]
Looking at how other jQuery dependent scripts do this, I think you’re right. I’ll see if I can make this happen.

**Comment by edemaine** [comment]
@cferdinandi Great! I don't think it's that hard -- you just need to test for `top` being above, but not restrict `bottom`. You may also need to go through the items in order instead of reverse order as you currently do.

In case it's helpful, [here's some code](https://github.com/mmistakes/minimal-mistakes/blob/master/assets/js/_main.js#L91-L125) I wrote to do this recently (but based on jQuery).  That project is hoping to replace this code with Gumshoe.

**Comment by cferdinandi** [comment]
Alright, just added support for this with v5.1.0: https://github.com/cferdinandi/gumshoe/releases/tag/v5.1.0
