### ISSUE TITLE
Fixed header offset demo missing

### ISSUE THREAD

**Issue by amdad** [cferdinandi/gumshoe#98]
Just look here: https://codepen.io/cferdinandi/pen/eXpLqo
Also that needs to update to v5. But even then if I paste code from docs it doesn't seems to work anyway. Offset is ignored. :)

**Comment by cferdinandi** [comment]
Ah, I had forgotten to add an `offset` option to the instantiation. Fixed. Thank you!

**Comment by amdad** [comment]
Thank you, but sorry, it's still doesn't work. I tried to update on codepen to @5.1, but it doesn't help. Also downloaded Github repo and opened it on local to be sure latest package and demo code for fixed headers I got. and it also didn't help.

**Comment by cferdinandi** [comment]
The linked demo above is working exactly as I'd expect it to in Chrome, Firefox, and Safari. See the screen capture below.

![offset](https://user-images.githubusercontent.com/1724852/54303430-57641380-4599-11e9-95e2-eb3b81613aba.gif)

What browser/OS are you using?

**Comment by amdad** [comment]
Oh, you're right, I forgot that there is no [SS](https://github.com/cferdinandi/smooth-scroll) here! Everything is A OK! Thanks ;) Anyway that would be cool to see combined demo of those two. Since this reflow option of gumshoe should be mirrored by SS.

**Comment by jtholloran** [comment]
@cferdinandi When simply scrolling, the offset works. But in that demo (https://codepen.io/cferdinandi/pen/eXpLqo), when you actually click one of the nav items, the content block doesn't take the offset into account and the top of the content block is hidden beneath the header. Possible to fix that?

**Comment by cferdinandi** [comment]
@jtholloran Hi there... that would require using a smooth scrolling library ([like this one](https://github.com/cferdinandi/smooth-scroll)) that accounts for the offset instead of the native CSS approach I used.
